### ISSUE TITLE
Complemento de la Recepción : ITC Steelgo , Cedula y Acero

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#10]
al momento de modificar el diametro para un numero unico en Complemento de la recepción mara el siguiente error: "No todos los registros cuentan con un itemcodesteelgo que coincida con los datos que se desea aplicar", siendo que ese item code ya se encuentra asociado con un itemcodesteelgo.
igualmente en la parte de packing list nuestro item code dado de alta cuenta con cedula y tipo de acero,pero en complemento de la recepción aparece sin ninguno de esos datos.
![cedula_acero_1](https://user-images.githubusercontent.com/24903990/30925263-e72c7e1a-a376-11e7-87e4-3ff2e7115268.JPG)
![itemcodesteelgo_1](https://user-images.githubusercontent.com/24903990/30925262-e72c181c-a376-11e7-87b5-787270ac029f.JPG)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)

**Comment by MiriamdeLeon-Steelgo** [comment]
Ruben los cambios solo lo hiciste en el Item que te mande foto?
 porque cheque otros y estan sin la cedula y el tipo de acero, pero el item "pruebaredu3" ya esta ok
![diapositiva1](https://user-images.githubusercontent.com/24903990/31085658-6815cc18-a75d-11e7-857d-dad9a1e28c48.JPG)
![diapositiva2](https://user-images.githubusercontent.com/24903990/31085657-6812548e-a75d-11e7-8177-26bec39f4855.JPG)

**Comment by MiriamdeLeon-Steelgo** [comment]
![error_cedula_acerp](https://user-images.githubusercontent.com/24903990/31095804-ae7e444c-a77f-11e7-87a2-998862ed0141.jpg)

Continua el error , en este item , cree un nuevo folio y todo y dentro del complemente de la recepcion encontre un solo item que no aparece la cedula y el tipo de acerp
