### ISSUE TITLE
Preparacion Emb : No Prep 

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#105]
al momento de guardar pide el nuevo embarque

![imagen](https://user-images.githubusercontent.com/24903990/32919079-321ad710-caea-11e7-9d7b-58128785eaac.png)

se llenan los datos, y al buscarlos en la preparacion, no aparece
![nopreparacion](https://user-images.githubusercontent.com/24903990/32919157-6f69f9ac-caea-11e7-8545-f9265ad9a7dc.jpg)

**Comment by emartinezd** [comment]
Lo puedes revisar en el nuevo ambiente por favor? es que acabo de hacer el proceso y si me salio
