### ISSUE TITLE
Complemento de la recepción : Guardar

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#11]
![carga_lenta](https://user-images.githubusercontent.com/24903990/30941432-02d7efe4-a3ab-11e7-99fc-b3bd3d72071a.jpg)

en complemento de la recepcion (con alrededor de 477 item) se le dio en guardar y van aproximadamente 15 min cargando

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)

**Comment by MiriamdeLeon-Steelgo** [comment]
@RojasRuben  , estoy guardando un nuevo folio con item code nuevos es el 12137-1, lleva alrededor de 30 hora cargando

**Comment by MiriamdeLeon-Steelgo** [comment]
![cargalenta1](https://user-images.githubusercontent.com/24903990/31190982-5254d47c-a902-11e7-819e-55aec13a1d39.jpg)
