### ISSUE TITLE
Armado: Taller

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#110]
![taller](https://user-images.githubusercontent.com/24903990/32955896-e9102fa0-cb7c-11e7-8ff9-685b60bb51c8.jpg)

No despliega los taller , siendo que en BD si estan
![imagen](https://user-images.githubusercontent.com/24903990/32955932-07e66dea-cb7d-11e7-96ad-da8017936709.png)

**Comment by emartinezd** [comment]
ACUERDATE QUE LA BD DE Sam3 ya no es la misma a donde consultabas, no habia info por eso 
se esta migrando de nuevo todo
