### ISSUE TITLE
Captura Pruebas por Lote: Proceso

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#113]
![pruebaslote](https://user-images.githubusercontent.com/24903990/33080094-daef0fcc-ce9c-11e7-8055-c4fc7f46f09e.jpg)

hace falta la de acabado

**Comment by RojasRuben** [comment]
@MiriamdeLeon-Steelgo La regla para obtener  los procesos es la siguiente.

Obtengo todos los procesos de pintura que tiene un sistema de pintura asignado a un spool y que ya tiene capturado avance en dicho proceso.

Ejemplo si un spool pertenece a etileno y solo tiene el proceso de shotblast en el sistema de pintura y después se captura el avance entonces en la pantalla de pruebas por lote al seleccionar el proyecto de etileno solo aparecerá Shotblast.
