### ISSUE TITLE
Liberacion Dimensional: BD

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#123]
Se captura una inspeccion dimensiona , por ejemplo el X030-001
![imagen](https://user-images.githubusercontent.com/24903990/33154237-b1890316-cfac-11e7-8376-9c6c8cd658ee.png)

pero se checa en la BD y no se refleja
![imagen](https://user-images.githubusercontent.com/24903990/33154267-dd472d16-cfac-11e7-8fa4-9768270630d5.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/33184553-bec36454-d042-11e7-9881-21724f2aaac1.png)

![imagen](https://user-images.githubusercontent.com/24903990/33184566-d16db848-d042-11e7-81ba-1aeb46c735d8.png)


me sigue apareciendo en 0 y ya cuenta

**Comment by MiriamdeLeon-Steelgo** [comment]
perdon lo que no tiene es visual
![imagen](https://user-images.githubusercontent.com/24903990/33184677-6053cc14-d043-11e7-9fb4-6d3651769114.png)

**Comment by emartinezd** [comment]
ABRE OTRO BUG, POR LO DE VISUAL,  NO ES LO MISMO
