### ISSUE TITLE
Embarque: Preparacion Emb - Plana

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#124]
al agregar una preparacion y guardar 
se borra la plana, mas no en el grib

![imagen](https://user-images.githubusercontent.com/24903990/33154460-108a349c-cfae-11e7-9a7f-949ed27feba6.png)

**Comment by emartinezd** [comment]
Eso no es error, obvio desaparece por que ya esta en un embarque  o preparcion la plana (en este cas en la preparacion  "Prep Jose" ), y no es viable a seleccionar en otro embarque hasta que se termine su proceso
