### ISSUE TITLE
Inspeccion Dimensional: Combobox

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#126]
al agregar  el numero de control y querer poner por ejemplo el X001-011, no hace la seleccion correcta
![diapositiva1](https://user-images.githubusercontent.com/24903990/33224821-300aae74-d133-11e7-849a-41befb33d01a.JPG)
![diapositiva2](https://user-images.githubusercontent.com/24903990/33224822-303740a6-d133-11e7-8c10-66f2462b7b03.JPG)

**Comment by emartinezd** [comment]
pero este no era el caso o si? esto si lo hace
