### ISSUE TITLE
NEWM: Inspeccion Dimensional: Foco

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#127]
al seleccionar por ejemplo el calendario, lo selecciono y me direcciona hasta el principio, siendo que se debe quedar donde se selecciono
![foco2](https://user-images.githubusercontent.com/24903990/33224902-4679c9be-d134-11e7-8288-5d558d37ef80.jpg)
![foco](https://user-images.githubusercontent.com/24903990/33224907-4d8f026e-d134-11e7-8e11-495fdbf80370.jpg)

**Comment by emartinezd** [comment]
![imagen](https://user-images.githubusercontent.com/14182815/33276357-fbc82310-d35a-11e7-9d96-3398f2433c83.png)

Definity lo que hace es  dependiendo de la celda en la que se encuentra, pone el focus en la siguiente columna, no es una funcion general, lo hacen en sus grids individuales, por columnas, dejo el ejemplo de Packing List (Vista cuantificacion)

**Comment by MiriamdeLeon-Steelgo** [comment]
ok, hazlo :)

**Comment by emartinezd** [comment]
Subi un ejemplo en Visual Dimensional, para esto del foco, lo podrian revisar por favor

**Comment by MiriamdeLeon-Steelgo** [comment]
ya lo cheque y funciona

**Comment by emartinezd** [comment]
Esto lo requieren en todas las pantallas?

**Comment by MiriamdeLeon-Steelgo** [comment]
si

**Comment by MiriamdeLeon-Steelgo** [comment]
en NEWM el error persiste
