### ISSUE TITLE
Inspeccion Visual-Dimensional : Resultado

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#130]
al quitar el rechazo negativo, y dejarlo en limpio , el rechazo no se quita, se sigue quedando

![imagen](https://user-images.githubusercontent.com/24903990/33225378-dff3c994-d13b-11e7-9fe8-59064a8832ec.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/33288083-9e7d5718-d380-11e7-97d7-a7f0b4f3059c.png)


dejo blancos y aprobados, unas juntas, al darle guardar

![imagen](https://user-images.githubusercontent.com/24903990/33288117-bceb312a-d380-11e7-9a84-dfe5c78deb90.png)


me deja los que deje en blanco como estaban antes

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/33288083-9e7d5718-d380-11e7-97d7-a7f0b4f3059c.png)


dejo blancos y aprobados, unas juntas, al darle guardar

![imagen](https://user-images.githubusercontent.com/24903990/33288117-bceb312a-d380-11e7-9a84-dfe5c78deb90.png)


me deja los que deje en blanco como estaban antes

**Comment by emartinezd** [comment]
Pues te sale el mensaje, que no se guardaran, no? por que por lo que veo, esta parcial la captura, entonces recupera la informacion de antes

**Comment by MiriamdeLeon-Steelgo** [comment]
pero  si quito todos , me los deja igual, como cuando yair hizo el ejemplo

**Comment by emartinezd** [comment]
TE SALE EL MENSAJE SI O NO ?

**Comment by emartinezd** [comment]
si el issue, es que los dejas en blanco manualmente y te sale que esta mal el renglon, ese es el issue, el cual no esta levantado de tal manera!!!

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/33351727-c7c94506-d46a-11e7-9a92-6fb6dc7a8f02.png)


le quito todo de resultado y por default los defectos

mesale este msj
![imagen](https://user-images.githubusercontent.com/24903990/33351745-e1a4fb78-d46a-11e7-811d-ff1c5639f5d2.png)

le dpy que si y me regresa a lo mismo

![imagen](https://user-images.githubusercontent.com/24903990/33351756-eda378dc-d46a-11e7-9dbd-219f37072630.png)

**Comment by emartinezd** [comment]
Obviamente, si te dice que no guardara los cambios, recarga la pantalla y contenido, con lo ultimo guardado

**Comment by emartinezd** [comment]
como guarda 2 secciones, guarda, aunque no tengas nada para guardar del grid
