### ISSUE TITLE
Inspeccion Visual Dimensional: JuntaR

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#132]
![imagen](https://user-images.githubusercontent.com/24903990/33225407-78508d80-d13c-11e7-9c8f-82c7f78de0a6.png)

actualmente la tabla con esta preparada para tener juntas en R, lo cual lo debe tener ya que puede haber juntas en reparacion que se inspeccionen

**Comment by MiriamdeLeon-Steelgo** [comment]
no puedo hacer la prueba, ya que necesito darle fecha a una junta de reparacion y en la app no cuenta con las juntas R
![imagen](https://user-images.githubusercontent.com/24903990/33287203-90ca3b84-d37d-11e7-9840-f38a55224b79.png)
![imagen](https://user-images.githubusercontent.com/24903990/33287261-c5d8243a-d37d-11e7-9948-52f0b53f8de2.png)

**Comment by emartinezd** [comment]
Lo deje asi, por que es por historial este modulo, asi que sera con base en la fecha de reparacion y la fecha de captura

**Comment by MiriamdeLeon-Steelgo** [comment]
pero en la app no aparece la junta R

**Comment by emartinezd** [comment]
Necesita ser la junta final, tiene habilitado ese campo?

**Comment by emartinezd** [comment]
estas consultando donde no es...

esto se consulta en Sam3_JuntaWorkStatus no en SAM

**Comment by MiriamdeLeon-Steelgo** [comment]
ok, deja checo

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/33351885-94017a58-d46b-11e7-8c24-4e019c28862f.png)

no hay nada insertado, lo tengo que insertar??
