### ISSUE TITLE
Embarque - Carga Plana : Numero de Control

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#137]
![imagen](https://user-images.githubusercontent.com/24903990/33448306-3f4b9d0c-d5cb-11e7-9d4b-55b37bf448f6.png)
al seleccional el spoolid (numero de control )  en la carga plana me dice que la orden no existe, siento que acabo de encitar ese numero de control

**Comment by emartinezd** [comment]
Cual orden es?

**Comment by MiriamdeLeon-Steelgo** [comment]
OD002
