### ISSUE TITLE
Embarque- Encintado : Cuadrante

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#138]
![imagen](https://user-images.githubusercontent.com/24903990/33448330-546c49ac-d5cb-11e7-80a3-44d2a2b98c49.png)

al desplegar el combobox,. no se despliega ningun cuadrante, siendo que en otro proyecto (etileno) si se desglozan los cuadrantes

![imagen](https://user-images.githubusercontent.com/24903990/33448548-f03aaa36-d5cb-11e7-8673-53587644a34b.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
Pregunta.-
De donde sacas esos cuadrante??
porque en la tabla cuadrantes , filtrando por patio , tengo estos cuadrantes
![imagen](https://user-images.githubusercontent.com/24903990/33518058-7b805b8e-d754-11e7-9ac5-07bf8e9889cf.png)


y en la app no aparecen
![nocuadrante](https://user-images.githubusercontent.com/24903990/33518069-a50a6f08-d754-11e7-95a2-02c5bfc18a87.jpg)

**Comment by jgutierrez01** [comment]
Es un query que tiene relacion con las tablas Rel_Usuario_Proyecto, Rel_Patio_Proyecto, Rel_Patio_zona
es el siguiente:
SELECT DISTINCT
  C.CuadranteID,
  C2.CuadranteID CuadranteSam2ID,
  C.Nombre,
  C.PatioID,
  P.ProyectoID,
  D.ZonaID
 FROM  Sam3_Proyecto P WITH(NOLOCK) 
  INNER JOIN Sam3_Rel_Usuario_Proyecto RUP WITH(NOLOCK) ON P.ProyectoID = RUP.ProyectoID AND RUP.UsuarioID = @Usuario
  INNER JOIN Sam3_Rel_Patio_Proyecto RPP WITH(NOLOCK) ON RPP.ProyectoID = P.ProyectoID AND  RPP.Activo=@Activo
  INNER JOIN Sam3_Rel_Patio_Zona RPZ WITH(NOLOCK) ON RPZ.PatioID = RPP.PatioID
  INNER JOIN Sam3_Zona D WITH(NOLOCK) ON RPZ.ZonaID = D.ZonaID AND D.Activo = @Activo OR D.Nombre LIKE @SL
  INNER JOIN Sam3_Cuadrante C WITH(NOLOCK) ON D.ZonaID = C.ZonaID AND C.Activo = @Activo 
  INNER JOIN SAM2.SAM.dbo.Cuadrante C2 WITH(NOLOCK) ON C2.Nombre LIKE C.Nombre COLLATE Modern_Spanish_CI_AS 
 WHERE  P.ProyectoID = @ProyectoID AND  P.Activo = @Activo  order by C.Nombre

porfavor validar si es correcto esta forma.

**Comment by jgutierrez01** [comment]
Por favor validar este detalle, si solamente es en algunos proyectos o en todos
