### ISSUE TITLE
S1:00021 @Resolver Incidencia

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#14]
![incidencia](https://user-images.githubusercontent.com/24903990/31298093-20aca528-aaae-11e7-8d73-c83d92fe0c36.jpg)

al darle guarda a la respuesta, me marca el siguiente error

**Comment by emartinezd** [comment]
Me puedes mostrar el caso completo? por que no me sale el error ni en QA por fav

**Comment by MiriamdeLeon-Steelgo** [comment]
el error aparece en el tipo de incidencia de item code y NU

**Comment by MiriamdeLeon-Steelgo** [comment]
al eliminar  el archivo , le doy en guardar , y al editar me quita la descripcion en ingles del archivo
![imagen](https://user-images.githubusercontent.com/24903990/31509453-22d54344-af47-11e7-9adc-8ac9a74d8f76.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/31510310-efdb0778-af49-11e7-97b3-e7e905fbdef3.png)
 

el error persiste en respuesta
