### ISSUE TITLE
Embarque: Carga Plana - Hold

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#142]
Se agrega el spool X090-001, Y manda un msj que no existe el spool , siendo que si existe y esta en hold
![imagen](https://user-images.githubusercontent.com/24903990/33491629-797324b8-d680-11e7-97bb-a7a07d255bea.png)

![imagen](https://user-images.githubusercontent.com/24903990/33491669-946cfc6c-d680-11e7-9a10-0f28f5121bbc.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
aun me deja agregar spool con hold
![imagen](https://user-images.githubusercontent.com/24903990/33518286-07e84368-d758-11e7-8185-82bf8a98ed84.png)
![imagen](https://user-images.githubusercontent.com/24903990/33518293-10bec002-d758-11e7-82ae-56bb81dd8b32.png)

**Comment by jgutierrez01** [comment]
Por favor Validar nuevamente
