### ISSUE TITLE
Embarques: Revision Embarque- Proyecto

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#148]
donde puedo dar de alta otro proyecto ? porque solo me aparece etileno
![no emb](https://user-images.githubusercontent.com/24903990/33518328-bafd26b2-d758-11e7-8d92-c620f91b87dc.jpg)

**Comment by jgutierrez01** [comment]
Los proyectos se obtienen mediante la relacion usuario proyecto y solamente se muestran aquello que requieren revision del cliente

SELECT 
		R.ProyectoID,
		Nombre,
		P.PatioID
	FROM dbo.Sam3_Proyecto P
	INNER JOIN dbo.Sam3_Rel_Usuario_Proyecto R WITH(NOLOCK) ON P.ProyectoID = R.ProyectoID
	INNER JOIN dbo.Sam3_ProyectoConfiguracion PC WITH(NOLOCK) ON PC.ProyectoID = R.ProyectoID
	WHERE P.Activo = @Activo AND R.UsuarioID = @UsuarioID AND PC.RequiereRevisionCliente = @RequiereRevisionCliente
	ORDER BY Nombre

**Comment by MiriamdeLeon-Steelgo** [comment]
entonces el proyecto lo debo insertar en Sam3_ProyectoConfiguracion  ??

**Comment by jgutierrez01** [comment]
debe de estar ahí para la validacion de aquellos proyectos que requieran revision de cliente, si no esta en esa tabla ó si existen pero no requieren revision, entonces no obtendra el proyecto.
