### ISSUE TITLE
S1:00021 @Respuesta Incidencia

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#15]
![respuestaincidencia](https://user-images.githubusercontent.com/24903990/31298346-69808106-aaaf-11e7-9535-c448214de2fc.jpg)

en respuesta de incidencia , no me deja eliminar los archivos adjuntos

**Comment by SAMBugs** [comment]
Me puedes mostrar el caso completo? por que no me sale el error ni en QA por favor
