### ISSUE TITLE
SHOP: Guardar

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#155]
al agregar spool en un SQ , se le da guardar y sale el siguiente msj
![imagen](https://user-images.githubusercontent.com/24903990/33782968-61b4482a-dc20-11e7-8a88-b362de873b54.png)

**Comment by jgutierrez01** [comment]
Hola @MiriamdeLeon-Steelgo  podrias describir el escenario donde hiciste esta prueba, ya que yo realizé el mismo procedimiento y me permitió actualizar correctamente
