### ISSUE TITLE
NEWM Captura PL: Carga masiva

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#158]
Al cargar el CSV por medio de carga masiva
no despliega ninguna informacion
![imagen](https://user-images.githubusercontent.com/24903990/34017264-a97769de-e0ea-11e7-8825-b405135186f5.png)

![imagen](https://user-images.githubusercontent.com/24903990/34017271-b1221cb0-e0ea-11e7-9860-c4b5d8b19183.png)

**Comment by RojasRuben** [comment]
Recuerda miriam que algunos itemcodes en base de datos estan repetidos, el item code incorrecto para este caso es : yaiiiiirra�oooorv
