### ISSUE TITLE
NEWM Captura PL: Interfaz

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#159]
la interaz es diferente a la de produccion en añadir itcs
produccion:
![imagen](https://user-images.githubusercontent.com/24903990/34019665-b25049ee-e0f5-11e7-8f51-3889a26ecf58.png)

newm
![imagen](https://user-images.githubusercontent.com/24903990/34019678-bf8645aa-e0f5-11e7-9ac8-96566bd90614.png)

**Comment by emartinezd** [comment]
Se cambiaron los estilos, a los generados por mafte, por eso
