### ISSUE TITLE
S1:0023 Creacion de OC

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#17]
![oc materiales](https://user-images.githubusercontent.com/24903990/31412312-32282280-adda-11e7-8b7e-9ef126304414.jpg)

Me marca este itemcode, que en el archivo CSV , no se encuentra

**Comment by SAMBugs** [comment]
Me podrias mandar el CSV de la carga para corroborar con pruebas por favor

**Comment by emartinezd** [comment]
Solucion sera: Si aparece un renglon completamente en blanco, ignorarlo y no agregarlo al grid
