### ISSUE TITLE
NEWM Requisicion de inspeccion de pintura- Hold

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#171]
tengo el spool F159-004 en hold
![imagen](https://user-images.githubusercontent.com/24903990/34178278-399fda3e-e4cc-11e7-8fa1-788424d30280.png)

lo agrego a requisicion pintura y me deja agregarlo, siendo que esta en hold
![imagen](https://user-images.githubusercontent.com/24903990/34178304-5480d448-e4cc-11e7-8f72-8ca3cb0b960c.png)

**Comment by jgutierrez01** [comment]
Ya subí la versión podrias validar este issue por favor, gracias saludos.
