### ISSUE TITLE
SHOP- Botone diseños

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#172]
los diseños estan diferentes
![imagen](https://user-images.githubusercontent.com/24903990/34221782-de631dbc-e57e-11e7-9d88-a37342e1cad7.png)

en produccion estan mas chicos y acomodados
![imagen](https://user-images.githubusercontent.com/24903990/34221836-ff9c11e6-e57e-11e7-8107-b3440aa4abc2.png)

**Comment by jgutierrez01** [comment]
Esta vista esta diseñada para móviles, si entras a tu navegar y pulsas F12 te aparecerá la ventana de desarrollador
![image](https://user-images.githubusercontent.com/27745795/34222709-11600a9c-e582-11e7-82e7-bf8fe0357d6f.png)

de esta manera podras observar como se observaría en diferentes tamaño de pantallas,
si creeen que esta mal se tendria que volver a diseñar la parte de los elementos de la pantalla
