### ISSUE TITLE
SHOP: SI Cliente

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#173]
en shop pruebas
al agregar un numero de control F001-001, sale el msj que el spool ya tiene un SI cliente Agregado
![imagen](https://user-images.githubusercontent.com/24903990/34222329-d8c7444e-e580-11e7-874f-af65a899d840.png)

pero al checarlo en la bd, ese numero de control, no tiene Sq interno
![imagen](https://user-images.githubusercontent.com/24903990/34222358-f538dec6-e580-11e7-8c02-ce06c28bcb44.png)

**Comment by jgutierrez01** [comment]
Hola @MiriamdeLeon-Steelgo el spool tiene Sq Cliente es decir el campo sq de la tabla Spool. por tal motivo no lo agrega, por favor verificar esta información, saludos.
