### ISSUE TITLE
NEWM: OK Pintura- Carga Masiva

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#174]
Al subir un archivo CSV , no aparece nada en el grib
![imagen](https://user-images.githubusercontent.com/24903990/34236471-5997c4ea-e5bd-11e7-9789-bfc33a0196e5.png)

esto es lo que regresa
![imagen](https://user-images.githubusercontent.com/24903990/34236483-63ae3cca-e5bd-11e7-950c-2b721646092d.png)

pero esos numeros de control si existen, porque se sacaron de un seguimiento de juntas

**Comment by RojasRuben** [comment]
Miriam cuando cargas por csv , no aparecera nada en el grid. por esa razon esta el sistema regresa un archivo como resultado.

**Comment by jgutierrez01** [comment]
Podrías validar nuevamente, saludos.
