### ISSUE TITLE
NEWM: Condiciones climatologicas- Equipos

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#179]
Actualizo los equipos
![imagen](https://user-images.githubusercontent.com/24903990/34276363-bc44c198-e666-11e7-80a0-5fee8e81a9e8.png)

pero en los equipos de temp. ambiente y temp del sustrato no aparecen, donde la configuro? o esta mal?

**Comment by RojasRuben** [comment]
![image](https://user-images.githubusercontent.com/32275317/34305221-9c31d4ee-e702-11e7-9fd5-1554015621e7.png)
te faltaba realizar estas relaciones. 
![image](https://user-images.githubusercontent.com/32275317/34305270-f755952c-e702-11e7-9e3c-28bdccab4b8b.png)
