### ISSUE TITLE
NEWM: Revision Embarque- Proyectos

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#180]
![imagen](https://user-images.githubusercontent.com/24903990/34279335-edff02ac-e675-11e7-9c7c-99c2341dce23.png)

No aparecen ningun proyectos en revison embarque

**Comment by jgutierrez01** [comment]
Aqui aparecen aquellos proyectos que requieren revision de cliente, se tiene que verificar en la tabla ProyectoConfiguracion aquellos que requieran revisionCliente

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/34313628-27706906-e732-11e7-92fe-88c412384a79.png)


Si tiene revision cliente

**Comment by jgutierrez01** [comment]
hola @MiriamdeLeon-Steelgo  es probable que cuando hiciste la preparacion del embarque, el proyecto aún no contaba con la bandera de RequiereRevisionCliente, y por lo tanto ese embarque se guardó con un status enviado y en revision de embarque requiere un estatus pendiente o en transito, en pocas palabras vuelve a crear una preparacion con el mismo proyecto y asi se podrá visualizar en revision embarque.
