### ISSUE TITLE
NEWM: Asignacion de envio- Proveedor

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#181]
![imagen](https://user-images.githubusercontent.com/24903990/34279388-2e3d6106-e676-11e7-8169-6e8adacb0996.png)

no despliega ningun proveedor y ninguna preparacion

**Comment by jgutierrez01** [comment]
El proyecto ya tiene alguna preparación creada?

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/34302262-cfb6f4f0-e6f5-11e7-9653-0fb7ae72facf.png)


si , se llama PREPMIRIAM
