### ISSUE TITLE
NEWM- Ok pintura : Hold

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#182]
Al querer agregar un spool con hold, me deja agregarlo
![imagen](https://user-images.githubusercontent.com/24903990/34384878-9d336b4c-eae4-11e7-8b4a-e92834a7be8f.png)
![imagen](https://user-images.githubusercontent.com/24903990/34384893-b0f9838c-eae4-11e7-8ca3-409c6258eaa6.png)

**Comment by jgutierrez01** [comment]
Puedes validar nuevamente, ahora no te apareceran los spools que tienen Hold ingenieria
