### ISSUE TITLE
NEWM : Orden de recepcion 

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#183]
Al generar una orden de recepcion, me marca el siguiente msj.
el folio es nuevo y los itemcode tambien

![imagen](https://user-images.githubusercontent.com/24903990/34393600-26d5e9ea-eb19-11e7-8d61-faa32ddf835d.png)

**Comment by RojasRuben** [comment]
miriam genere un nuevo folio y genere los numeros unicos.

![image](https://user-images.githubusercontent.com/32275317/34413208-88ed1b60-eba7-11e7-949e-f7e924b00d0a.png)
