### ISSUE TITLE
NEWM-Ok Pintura- Grib

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#186]
Pregunta
en el grib de ok pintura, no aparece la informacion de primario,intermedio y acabado
siendo que si estan capturados
![imagen](https://user-images.githubusercontent.com/24903990/34395652-ab032d00-eb27-11e7-82ba-10b09b9059b9.png)
![imagen](https://user-images.githubusercontent.com/24903990/34395656-b52dcbb4-eb27-11e7-83d9-a7679bbce469.png)

**Comment by jgutierrez01** [comment]
Hola @MiriamdeLeon-Steelgo podrías validar nuevamente este issue, gracias saludos.
