### ISSUE TITLE
Avance Trineo: Lentitud

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#199]
Al dar en guardar en cada proceso (shotblast, primario, acabado,intermedio), tarda como entre 4-5 min en guardar
![imagen](https://user-images.githubusercontent.com/24903990/35286151-d5031734-0024-11e8-9c24-7f50d7ff9b8a.png)

**Comment by RojasRuben** [comment]
Miriam como te comente , este issue esta relacionado a la red yo hice la prueba y carga muy rapido, la prueba que hice fue en producción.

**Comment by MiriamdeLeon-Steelgo** [comment]
Lo checare con @yairSteelgo  porque estando en materiales fue cuando se alento, pero ahorita en newm y estando en mi lugar no va lento
