### ISSUE TITLE
Orden de Recepción : Accesorios

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#2]
![ordenrecepcion_error1](https://user-images.githubusercontent.com/24903990/30924013-15a1f620-a373-11e7-8dec-57debb86c6fb.jpg)
Se guardo la item para generar la orden de recepción, al guardar los tubos no hubo ningun problema, pero al guardar los accesorios marco error "Mensaje de error: Error al generar los numeros unicos."

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)
