### ISSUE TITLE
Generales : Ajustar texto en pantalla

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#201]
Todas las pantallas que tienen grid tiene que contar con el Ajustar en texto en los titulos

![imagen](https://user-images.githubusercontent.com/24903990/35309060-2e3acc84-0070-11e8-8f5e-7830abd1b166.png)

**Comment by emartinezd** [comment]
Con la modificacion realizada ayer a los estilos, las pantallas de materiales no necesitan el "Ajustar texto", esa funcionalidad quedan unicamente para las pantallas de capturas rapidas, en las cuales si esta implementado
