### ISSUE TITLE
Pintura: Avance Cuadrante

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#202]
![imagen](https://user-images.githubusercontent.com/24903990/35363651-9ed26202-0130-11e8-9b2d-3c137192db41.png)

al momento de darle Mostrar, me dice que no tiene proyecto, siendo que se selecciona el proyecto

**Comment by SAMBugs** [comment]
@RojasRuben pq deja de funcionar en Prod y en QA si ? es error de version, configuracion o  programacion ?

**Comment by RojasRuben** [comment]
Hice pruebas y es por el proyecto , solo cuando selecciona ese proyecto truena entonces ya le cambie la programacion y ya puse la etiqueta de publicado para que se valide

**Comment by MiriamdeLeon-Steelgo** [comment]
sigue igual, tanto en carga de trineo 
![imagen](https://user-images.githubusercontent.com/24903990/35460469-c3b0c24c-02a9-11e8-9fd5-7119e265fb62.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
En NEWM
