### ISSUE TITLE
Pintura: Sistema de Pintura Aplicable

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#206]
![imagen](https://user-images.githubusercontent.com/24903990/35463658-5b8e8542-02b7-11e8-9716-bd53a56ec988.png)
![imagen](https://user-images.githubusercontent.com/24903990/35463693-8b1944f0-02b7-11e8-9858-680e1657a651.png)

al momento de darle Mostrar, me dice que no pertenece a ese proyecto, siendo que si existe ese numero de control
![imagen](https://user-images.githubusercontent.com/24903990/35463773-f6c0b328-02b7-11e8-8308-aa30596f84ae.png)

**Comment by RojasRuben** [comment]
Miriam porfavor revisa a que bd te estas conectando ya que ejecute el mismo query pero con el link server y no me arrojo ningun resultado. anexo evidencia.
![image](https://user-images.githubusercontent.com/32275317/35484980-2fae46d4-041e-11e8-8013-1f8857898419.png)

Por ultimo me estoy conectando al escritorio remoto 3397  al servidor "STEELGO-DB05\SAMSYSCOM"
y bd steelgo-sam3 ejecute el query 

--Query que se ejecuta para el modulo sistema de pintura aplicable
select  OTS.NumeroControl from  
	SAM2.SAM.dbo.Spool S WITH(NOLOCK) 
   INNER JOIN Sam3_EquivalenciaProyecto EPR WITH(NOLOCK) ON EPR.Sam2_ProyectoID=S.ProyectoID
   INNER JOIN SAM2.SAM.dbo.OrdenTrabajoSpool OTS WITH(NOLOCK) ON S.SpoolID = OTS.SpoolID 
   WHERE   EPR.Sam3_ProyectoID  = CAST(2009 AS varchar) AND OTS.NumeroControl LIKE '%'+'f002-001'+'%';
--Query que ejecutaste solo le agregue los link server
   select * from sam2.sam.dbo.ordentrabajospool a inner join sam2.sam.dbo.spool b on a.spoolid=b.spoolid
   inner join sam2.sam.dbo.proyecto c on b.proyectoid=c.proyectoid
   where a.numerocontrol='f002-001' and b.proyectoid=52

**Comment by MiriamdeLeon-Steelgo** [comment]
el servidor que usas de "STEELGO-DB05\SAMSYSCOM"
y bd steelgo-sam3 es el de NEWM . 
ejecute el query en sam3 (192.168.1.4) y me sale esto
![imagen](https://user-images.githubusercontent.com/24903990/35526948-c7ddbfcc-04ee-11e8-8b2a-1c58f08887f0.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
En Newm esta igual
proyecto CGA
![imagen](https://user-images.githubusercontent.com/24903990/35539760-8bbdfc12-0518-11e8-9a25-23c573f4d7db.png)

![imagen](https://user-images.githubusercontent.com/24903990/35539777-9be959ce-0518-11e8-844a-ffecdc65cce0.png)
![imagen](https://user-images.githubusercontent.com/24903990/35539790-a503f9ec-0518-11e8-8189-760ead726618.png)



ese numero de control si existe

**Comment by MiriamdeLeon-Steelgo** [comment]
Validado en NEWM

**Comment by MiriamdeLeon-Steelgo** [comment]
con el proyecto de prueba (Samprueba3) no hay ningun problema, pero con Demo sigue teniendo el mismo problema
![imagen](https://user-images.githubusercontent.com/24903990/35646304-5cab16a8-0694-11e8-8837-6465a69fe2fa.png)
