### ISSUE TITLE
Pintura: Carga Trineo : DSCG

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#210]
En produccion en carga trineo al querer darle click en el boton de DSCG no sale la pantalla que salia antes de la zona y cuadrante

![imagen](https://user-images.githubusercontent.com/24903990/35646879-512bc014-0696-11e8-8c66-95d5f77fa2b0.png)
 

asi es como salia:

![imagen](https://user-images.githubusercontent.com/24903990/35646905-64a21f9e-0696-11e8-8d09-487fe56f4e95.png)

**Comment by RojasRuben** [comment]
Miriam como te comente por conferencia hubo un problema al obtener el cuadrante fisico anterior , y se esta obteniendo el cuadrante movil anterior esto impacta en el modulo porque al obtener el cuadrante movil anterior no se puede mostrar el popup de descarga.

para obtener el ultimo cuadrante consultamos esta tabla.
select * from Sam2.sam.dbo.cuadrantehistorico where spoolid=

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/35707514-a3458810-076f-11e8-98c4-ea995453cf60.png)

me sale vacio

se tiene que insertar?
