### ISSUE TITLE
Pintura: Carga Trineo - Orden de trabajo SAM3PRUEBAS

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#211]
en carga trineo al poner la orden de trabajo para que salga el numero de control, dice que la orden de trabajo no fue encontraba, siendo que si existe
![imagen](https://user-images.githubusercontent.com/24903990/35647007-d0ba7aa0-0696-11e8-927e-3b786f943629.png)

![imagen](https://user-images.githubusercontent.com/24903990/35647032-e546afd4-0696-11e8-8086-fdc35b2e15d2.png)

**Comment by RojasRuben** [comment]
Podrías validar que el proyecto en sam2 se encuentre activo por favor

select * from Sam2.sam.dbo.Proyecto where proyectoid=44
