### ISSUE TITLE
S1:00023 Control de OC

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#22]
![imagen](https://user-images.githubusercontent.com/24903990/31691134-91f8209a-b35a-11e7-8cc1-f463d62dc814.png)

Dentro del usuario Cecilia (tiene permisos para capturar el UM en el alta de colada)
no me deje capturar dicho registro, solo el nombre de la colada, cantidad e insp

**Comment by MiriamdeLeon-Steelgo** [comment]
cuando poner tuberia si me sale la UM

**Comment by emartinezd** [comment]
Asi es la configuracion, solo te permite capturar la Unidad de Medida, si es tuberia, si no, no te lo permite
