### ISSUE TITLE
OC NEWM: Pintura- Pruebas x Spool

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#226]
sigue teniendo el boton de agregar spool 
![imagen](https://user-images.githubusercontent.com/24903990/36119000-642998e0-1004-11e8-8b0a-a59100a2b833.png)
![imagen](https://user-images.githubusercontent.com/24903990/36119013-6b018d26-1004-11e8-917b-b57b51d02197.png)

**Comment by RojasRuben** [comment]
No es un issue cuando un spool no tiene pruebas entonces si le quito el botón ¿como le va agregar las filas? por esa razon deje el botón.

**Comment by MiriamdeLeon-Steelgo** [comment]
Comenta yair que requiere que se haga lo que dice la orden de cambio 
![imagen](https://user-images.githubusercontent.com/24903990/36281632-ec025624-1263-11e8-98bc-bbe6fea3b14d.png)
