### ISSUE TITLE
OC NEWM- Pintura-: Avance trineo

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#227]
sigue teniendo las etiquetas de shotblastero y pintur , en lugar de operador

![imagen](https://user-images.githubusercontent.com/24903990/36119071-941ef8f6-1004-11e8-8752-81cccc7cd19f.png)

**Comment by RojasRuben** [comment]
Por favor de validar con yair , porque cuando se genero las ordenes de cambio indicaron el requerimiento pero yair realizo otra presentacion y es donde me pidio que dijera shotblastero y pintor.
¿cual requerimiento es es el que se  queda?

**Comment by MiriamdeLeon-Steelgo** [comment]
me comento yair que si se haga el cambio

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/36316810-f2648198-1300-11e8-9a7b-4621a274cae3.png)
En avance de trineo esta el cambio, pero por ejemplo en avance cruadrante, en primario, en la parte del grib sigue diciendo pintores, 
![imagen](https://user-images.githubusercontent.com/24903990/36316871-1b05d3a4-1301-11e8-8689-b5b85a915087.png)
igual en intermedio
![imagen](https://user-images.githubusercontent.com/24903990/36316892-331aec90-1301-11e8-9a94-f6dab113f9b7.png)
igual en shotblast
![imagen](https://user-images.githubusercontent.com/24903990/36316915-4694009a-1301-11e8-9ba2-42f0ec61f516.png)
