### ISSUE TITLE
Embarques- Revision Embarques : Etiqueta Embarque

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#237]
![imagen](https://user-images.githubusercontent.com/24903990/38109049-087d7e58-3354-11e8-80e7-6e94f5272995.png)

en el combobox  embarque, en lugar de mostrar los embarques, muestra los nombres de las preparaciones 

ejemplo Revision Embarque

**Comment by emartinezd** [comment]
Pero solo en esa pantalla se cambiaria, por que hasta antes del envio son preparaciones

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/38152718-3f882362-3426-11e8-9654-15ef1f54638a.png)
 Este es el msj que les decia, que dice emb y manda el nombre de la preparacion

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/38703997-79b228e6-3e6a-11e8-88c8-cafea5db6a47.png)

sigue estando este

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/38704349-a39878ee-3e6b-11e8-8691-efbbcf51f750.png)
en listado embarques cerrados , tambien en lugar de poner el embarque, poner la preparacion

**Comment by jgutierrez01** [comment]
En listado de Embarque Cerrados actualmente se muestra la preparación, se requiere mostrar el embarque (Capturado al momento de enviar)?

**Comment by MiriamdeLeon-Steelgo** [comment]
Si se muestra la preparacion , debe decir PREP

**Comment by snoguera** [comment]
Cerrado porque Miriam me dijo....
