### ISSUE TITLE
Menu de Embarque

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#239]
![imagen](https://user-images.githubusercontent.com/24903990/38109566-c9110166-3355-11e8-82a4-e1d172f67f27.png)

tienen que esta organizado, sin espacion grande entre dashboard y asignacion

El acomodo es asi:
Dashboard Embarque
Encintado
Carga Plana
Empaquetado
Preparacion Embarque
Revisión Embarque
Asigancion de Envío 
Listado Embarques Cerrados

**Comment by jgutierrez01** [comment]
En este caso nunca se me mencionó un orden para los items
