### ISSUE TITLE
Listado de Embarque

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#240]
El listado de embarque, mandarlo a Listados
![imagen](https://user-images.githubusercontent.com/24903990/38109714-4f26e248-3356-11e8-91c3-6353a23b1983.png)

**Comment by emartinezd** [comment]
Esto  nunca se habia dicho que yo recuerde

**Comment by jgutierrez01** [comment]
Desde que yo empecé a desarrollar nunca se mencionó este punto.
