### ISSUE TITLE
Embarque- Carga Plana - Lentitud

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#241]
Al momento de elegir el F001, tarda en mostrar los numeros de control
![imagen](https://user-images.githubusercontent.com/24903990/38109831-a560b788-3356-11e8-8f5d-c68a76bdbb9c.png)

contrario a que si pongo el f002 es inmediato
![imagen](https://user-images.githubusercontent.com/24903990/38109848-b37c9882-3356-11e8-9ab8-24f99dfd94bc.png)

**Comment by emartinezd** [comment]
Lo acabo de probar y funciona bien en varias ocasiones

**Comment by jgutierrez01** [comment]
Este detalle lo hiban a platicar en lado de sergio y yair, se tarda debido a los movimientos de cuadrantes, patios etc, (son interacciones entre las bases y esto obviamente tarda)

**Comment by MiriamdeLeon-Steelgo** [comment]
En un spool F1235-001 , tardo 32 seg
y en 6 spool 
F888-006
F888-005
F888-004
F888-003
F888-002
F887-001

Tardo 2.25 min
