### ISSUE TITLE
Embarque Proveedores

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#244]
Pregunta los proveedores de embarques, estan en la misma tabla que los de materiales??
![imagen](https://user-images.githubusercontent.com/24903990/38110647-8ea63c7c-3359-11e8-97eb-ecf03b622ec6.png)

si es asi, comenta yair que ya habia pedido que fueran separados.

**Comment by emartinezd** [comment]
Si, y ya se habia dicho, solo que hay 2 tablas, una llamada Sam3_TipoProveedor y otra llamada Sam3_Rel_Proveedor_TipoProveedor, donde esta la relacion de los que aparecen en estas pantallas, tambien ya se habia dicho

**Comment by MiriamdeLeon-Steelgo** [comment]
Me comenta yair, que lo que no quieres es que yo de de alta proveedores en embarques 
![imagen](https://user-images.githubusercontent.com/24903990/38117875-becf1318-3374-11e8-81d9-3b5c8d09ee0c.png)

y en materiales, esos proveedores aparezcan ( ya que son proveedores de embarques)
![imagen](https://user-images.githubusercontent.com/24903990/38117909-e4a85266-3374-11e8-9a71-9c41727a46ed.png)

que ya les habia comentado eso
