### ISSUE TITLE
Embarque - Carga Plana - Lentitud

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#247]
cuando se agrega un spool que esta en revision embarque , la pantalla de carga plana, se queda trabaja

![imagen](https://user-images.githubusercontent.com/24903990/38111176-4518ff48-335b-11e8-8403-bdcbf54bd347.png)

![imagen](https://user-images.githubusercontent.com/24903990/38111182-4bf04358-335b-11e8-8c5c-8d83f581ce30.png)

**Comment by emartinezd** [comment]
El spool esta como si no llego, segun tu logica, no esta certificado, por lo tanto se puede volver a cargar

**Comment by MiriamdeLeon-Steelgo** [comment]
En 9 spool tardo 4 min
