### ISSUE TITLE
Embarque- Revision Embarque : Embarques

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#250]
En revision embarque  aunque cierre y guarde, me sigue dejando los embarques
![imagen](https://user-images.githubusercontent.com/24903990/38220790-cca5266e-36a1-11e8-8184-1ce94e18aa09.png)

y no los pasa a listado de emb cerrados

**Comment by jgutierrez01** [comment]
Este así funciona, ya que yair pidió que la revisión se puede volver abrir y cerrar (si no aparece cómo se vuelve a editar?)

**Comment by MiriamdeLeon-Steelgo** [comment]
Estas en todo lo correcto fabian :)
