### ISSUE TITLE
NEWM - Eliminacion de preparacion

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#259]
Al eliminar la preparacion en el modulo de preparacion embarque, marca lo siguiente:
![imagen](https://user-images.githubusercontent.com/24903990/38701655-0a8940e0-3e64-11e8-9b78-fc9479b0977f.png)

en lugar de que mande un msj que la preparacion se eliminara, manda la siguiente pantalla
![imagen](https://user-images.githubusercontent.com/24903990/38701670-1c77add2-3e64-11e8-853f-073d7a00b73c.png)

y despues manda el siguiente msj
![imagen](https://user-images.githubusercontent.com/24903990/38701688-283d1a44-3e64-11e8-806a-a9682b91f9eb.png)

**Comment by emartinezd** [comment]
OC: Al momento de guardar una plana de la cual eliminas todas las planas, realizar la misma accion que cuando elimnas una preparacion con el mensaje de tipo warning "Esta accion eliminara la preparacion, desea continuar?" y eliminando la preparacion

**Comment by snoguera** [comment]
Solo se eliminará la preparación por medio del boton "Acciones" -> Eliminar Preparación
