### ISSUE TITLE
Carga Plana - Preparación embarque

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#260]
en una pestaña, abro carga plana y agrego 2 spool
![imagen](https://user-images.githubusercontent.com/24903990/38702370-1e285580-3e66-11e8-8249-a6ce6ef502ed.png)

y en otra pestaña tengo preparacion embarque, donde selecciono la plana y estan los 2 spool 
![imagen](https://user-images.githubusercontent.com/24903990/38702528-745e7b14-3e66-11e8-9bc2-38d32faa2aca.png)

le creo la preparacion y guardo
![imagen](https://user-images.githubusercontent.com/24903990/38702564-917d22cc-3e66-11e8-91e1-647b91f6f5d9.png)

por otro lado en la pestaña de carga de plana , abro la plana y descargo un spool , para que solo quede uno
![imagen](https://user-images.githubusercontent.com/24903990/38702609-ada00988-3e66-11e8-861a-b76e45924d7a.png)

![imagen](https://user-images.githubusercontent.com/24903990/38702634-bcf553de-3e66-11e8-9b57-51a611a2da64.png)

siendo que ya tenia guardado la preparacion

**Comment by emartinezd** [comment]
Esto no es bug, es algo que nunca se pidio validar!!!
