### ISSUE TITLE
NEWM Embarques- Seguimiento de juntas

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#262]
En el seguimiento de juntas de CGA, el spool G090-001 no aparece, y en shop ,sac y los demas reportes si aparece
![imagen](https://user-images.githubusercontent.com/24903990/38706509-0dff3b12-3e73-11e8-9c92-04ed032c0469.png)

![imagen](https://user-images.githubusercontent.com/24903990/38706517-12a6c5f4-3e73-11e8-8e0e-bce14b59e1f4.png)
![imagen](https://user-images.githubusercontent.com/24903990/38706524-159664fe-3e73-11e8-92df-3cc12ee4b362.png)

**Comment by snoguera** [comment]
Cerrado por indicación de Miri Miri Boom Boom
