### ISSUE TITLE
Reporte Emb - Seguimiento Spool Emb ( Numero de embarque)

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#265]
En el seguimiento spool Emb no refleja los embarques, y en el unico spool que si aparece, se refleja la preparacion
![imagen](https://user-images.githubusercontent.com/24903990/38906573-10f821cc-427d-11e8-9fcb-553316c2a607.png)
![imagen](https://user-images.githubusercontent.com/24903990/38906579-2481a6f0-427d-11e8-9b2a-018d155f7513.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
:)

**Comment by snoguera** [comment]
Cerrado porque Mir Miri Bool boom me dijo....

Reporte repetido
