### ISSUE TITLE
REVISION_EMBARQUE-Spool se mantiene en cuadrante movil 

### ISSUE THREAD

**Issue by Alejandra2492** [SAMBugs/Bugs#270]
En Revisión de Embarque, en la plana 1 se agrego el spool F023-001 y se capturo con "No llego" y se cerro.
![captura_1](https://user-images.githubusercontent.com/38543404/39327329-53733f00-495d-11e8-8843-df3ef4751c80.PNG)

y en la pantalla de Empaquetado al buscar el Spool F023-001 se coloca en el cuadrante Plana 1 
![captura_2](https://user-images.githubusercontent.com/38543404/39327386-800af51c-495d-11e8-81d2-199ab13fa0b5.PNG)

**Comment by jgutierrez01** [comment]
Esto ya esta validado por miriam
