### ISSUE TITLE
Revision de Embarque - Cambiar Spool de Embarque 

### ISSUE THREAD

**Issue by Alejandra2492** [SAMBugs/Bugs#271]
Al momento de cambiar un Spool a otra revisión no se mantiene en la revisión donde fue agregado 

En la revisión debería estar el spool F023-001 
![captura_3](https://user-images.githubusercontent.com/38543404/39333690-5c5aa57c-4971-11e8-97fd-ff4d3169b19f.PNG)

**Comment by jgutierrez01** [comment]
Esto ya esta validado por miriam
