### ISSUE TITLE
Carga Plana - Descargar Spool cargado en una revisión 

### ISSUE THREAD

**Issue by Alejandra2492** [SAMBugs/Bugs#272]
Se permitió descargar un Spool que ya estaba capturado en una revisión y permitió la descarga en la Pantalla de carga de plana que aun no se cerraba la pestaña (Validación en 2 navegadores)

![captura_4](https://user-images.githubusercontent.com/38543404/39333924-509b3f34-4972-11e8-8cd1-7cedef9b47ef.PNG)

**Comment by jgutierrez01** [comment]
Esto ya esta validado por miriam
