### ISSUE TITLE
SHOP - No refleja el embarque

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#273]
el spool F045-'001  en revision emb le puse que no llego
![imagen](https://user-images.githubusercontent.com/24903990/39668901-6af68326-50a1-11e8-9bb6-a803c9f9bfd8.png)

despues lo vuelvo a cargar en otro embarque , y le pongo que si llego
![imagen](https://user-images.githubusercontent.com/24903990/39668904-8b97aede-50a1-11e8-8585-5016730d875e.png)

y en el shop no se refleja el cambio

![imagen](https://user-images.githubusercontent.com/24903990/39668906-a107ae72-50a1-11e8-98fd-d383be6a1e85.png)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente
