### ISSUE TITLE
Shop - Embarque no reflejado en CGA

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#274]
![imagen](https://user-images.githubusercontent.com/24903990/39729361-0ba09cc8-5221-11e8-83f1-ecc7e33aa11a.png)

Este proyecto no tiene configurado la revision y ya se encuentra en embarque cerrado , pero en shop no se relfeja

![imagen](https://user-images.githubusercontent.com/24903990/39729390-3208bdb4-5221-11e8-85a3-294ede1f8d2c.png)

**Comment by jgutierrez01** [comment]
Favor de crear un nuevo embarque y despues validarlo
