### ISSUE TITLE
Seguimiento spool PYC : Datos triplicados

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#276]
![imagen](https://user-images.githubusercontent.com/24903990/39793035-37bc5e76-5309-11e8-82c4-e183a61c0df6.png)

mismo caso en seguimiento spool PYC,

**Comment by MiriamdeLeon-Steelgo** [comment]
igual es Franklin
![imagen](https://user-images.githubusercontent.com/24903990/39793172-e813c30e-5309-11e8-9c1a-968466024454.png)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente
