### ISSUE TITLE
Seguimiento Spool : Embarcados SI/NO

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#280]
![imagen](https://user-images.githubusercontent.com/24903990/39926889-37ccd794-54f6-11e8-9a67-9b6d63a45063.png)

Cuenta con embarque y en embarcados (SI/NO) dice que No

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/39961969-d6e338ac-5607-11e8-86e0-7a8f8bf421c2.png)
mismo caso
