### ISSUE TITLE
Seguimiento Spool PYC : Embarcado (SI/NO)

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#281]
![imagen](https://user-images.githubusercontent.com/24903990/39927436-ce2b7e56-54f7-11e8-9f83-6c026d831fc4.png)

mismo caso en seguimiento spool PYC , embarcados si/no , aparece que no y cuenta con embarque

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente

**Comment by MiriamdeLeon-Steelgo** [comment]
Cargados ya OK, embarcados si/no aun no

![imagen](https://user-images.githubusercontent.com/24903990/39961801-5b5feb84-5603-11e8-8abc-e9a62315d091.png)
