### ISSUE TITLE
Seguimiento spool Multiproyecto: Cargado (SI/NO) - Embarcado (SI/NO) 

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#282]
![imagen](https://user-images.githubusercontent.com/24903990/39928467-06ddbbbc-54fb-11e8-82b6-9565c6b49961.png)

mismo caso en seguimiento spool multiproyecto, tiene embarque, y en cargados y embarcados dice que no

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/39961719-045d6088-5602-11e8-8fe3-781d4a6aab01.png)

cargado ya esta,  embarcados no
