### ISSUE TITLE
Cobro X SQ100 : Datos super dobles

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#283]
en el reporte Cobro x SQ100 , los spoolid se ponen 14 veces
![imagen](https://user-images.githubusercontent.com/24903990/39930915-90ff983c-5501-11e8-9843-f17ad191890e.png)

**Comment by jgutierrez01** [comment]
Favor de Validar Nuevamente

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/39938049-43e502ba-5517-11e8-924c-4d1918a9ad19.png)

el spool F2055-003 no aparece 

![imagen](https://user-images.githubusercontent.com/24903990/39938106-6c62c876-5517-11e8-8817-923fe1aade24.png)

**Comment by jgutierrez01** [comment]
En que reporte es la imagen?

**Comment by MiriamdeLeon-Steelgo** [comment]
en seguimiento spool estan los 15 spool en el de cobro x sq100 solo 14

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente y verificar si la información es correcta
