### ISSUE TITLE
Cobro x Embarque : no aparece informacion

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#286]
Porque en el reporte de cobro x sq100 aparece valores
![imagen](https://user-images.githubusercontent.com/24903990/39942781-362f6e58-5526-11e8-8d4b-60ecc8052287.png)

y en el de cobro x embarque no
![imagen](https://user-images.githubusercontent.com/24903990/39942803-43ad4730-5526-11e8-8586-a3bba9c3538b.png)

**Comment by jgutierrez01** [comment]
Solamente se modificó la columna de  Shipping, las demás ya venían así, favor de revisarlo con  kevin o yair

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/39949867-42ba8352-5543-11e8-91fe-07100432ef1f.png)

el productivo trae informacion,

**Comment by MiriamdeLeon-Steelgo** [comment]
Sigue igual
![imagen](https://user-images.githubusercontent.com/24903990/40077684-07f6ed52-5848-11e8-9803-8fadb0c99993.png)
![imagen](https://user-images.githubusercontent.com/24903990/40077699-0fc8d266-5848-11e8-96de-e7947b0cfc9f.png)
