### ISSUE TITLE
Seguimiento Spool: No llego

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#287]
![imagen](https://user-images.githubusercontent.com/24903990/39944046-a4d4c3c2-552a-11e8-9b93-774e9a9d439c.png)
se puso el spool F2055-003 Como que no llego, y aparece con embarque en seguimiento spool

![imagen](https://user-images.githubusercontent.com/24903990/39944072-b820e578-552a-11e8-95ff-60d663c0f63d.png)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente
