### ISSUE TITLE
Seguimiento spool PYC : No llego

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#288]
mismo caso, el f2055-003 se puso que no llego y aparece en el reporte con embarque
![imagen](https://user-images.githubusercontent.com/24903990/39944245-90a8b2f4-552b-11e8-8a38-c7c311439e73.png)
![imagen](https://user-images.githubusercontent.com/24903990/39944263-a10cc7b6-552b-11e8-84e7-6da07c715dde.png)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente
