### ISSUE TITLE
Seguimiento spool multiproyecto:  no llego

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#289]
Mismo caso, el spool F2055-003 se puso que no llego, y aparece en el reporte con embarque
![imagen](https://user-images.githubusercontent.com/24903990/39944670-19079d9e-552d-11e8-88b7-04e9e3c7c712.png)

![imagen](https://user-images.githubusercontent.com/24903990/39944678-23259eca-552d-11e8-86ae-065d6682267c.png)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente
