### ISSUE TITLE
SAC: status spool

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#290]
![imagen](https://user-images.githubusercontent.com/24903990/39944926-11cac5a0-552e-11e8-915e-068617236544.png)

en status spool no hay nada, ni el proyecto puedo elegir

**Comment by jgutierrez01** [comment]
no conecta con la base del sam3 en QA, por favor de verificar con Kevin que cree el usuario de samreports

**Comment by MiriamdeLeon-Steelgo** [comment]
Al abrir la vista sale este msj

![imagen](https://user-images.githubusercontent.com/24903990/40023932-40805868-5792-11e8-86ee-4fe8a24fee83.png)

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/40077599-c2b71df2-5847-11e8-90eb-8f2ea4a80e9e.png)

Mismo caso en CGA

**Comment by jgutierrez01** [comment]
Favor de volver a validar
