### ISSUE TITLE
Seguimiento Dossier: Lento

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#291]
Tarda 15 min en cargar y en produccion 21 seg

![imagen](https://user-images.githubusercontent.com/24903990/39945435-10cd1412-5530-11e8-83de-28e5ecf9e539.png)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente

**Comment by MiriamdeLeon-Steelgo** [comment]
Ya no esta lento, pero no puedo terminar de validarlo porque tambien necesito el seguimiento de juntas
