### ISSUE TITLE
Reporte Salida Materiales: Doble

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#292]
en el spool F1889-003 tiene los item repetidos
![imagen](https://user-images.githubusercontent.com/24903990/40020341-75e11782-5787-11e8-9af9-597bb1359223.png)

siendo que en shop solo son 2 
![imagen](https://user-images.githubusercontent.com/24903990/40020401-962dd804-5787-11e8-977a-4d3250cbfb63.png)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente
