### ISSUE TITLE
Sistema Pintura Aplicable: NEWM

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#297]
Al guarda el sistema de pintura y color en un spool, marca el msj que "Los registros marcados no seran guardados ¿Desea continuar? "

ese sistema de pintura esta configurado por spool
![error 1 pintura](https://user-images.githubusercontent.com/24903990/42460199-ea74eda6-8362-11e8-8d2b-5117efe42c76.JPG)

**Comment by jgutierrez01** [comment]
Tienes que insertar el spoolID en la tabla Sam3_SP_SpoolAplicable

**Comment by MiriamdeLeon-Steelgo** [comment]
Error mio :)
