### ISSUE TITLE
Carga Trineo : NEWM

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#298]
Al cerrar la carga de trineo tarda 20 seg siendo que solo es 1 spool
![error 2 pintura tarda en cerrar](https://user-images.githubusercontent.com/24903990/42460278-0d649780-8363-11e8-95a7-33d16a43d0e2.JPG)

**Comment by jgutierrez01** [comment]
Favor de validar nuevamente
