### ISSUE TITLE
Captura Pruebas por spool: NEWM

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#299]
Al seleccionar el spool , proceso y prueba, le doy en buscar y marca el msj que el spool no tiene pruebas capturadas, siendo que si se capturaron
![error 3 pintura](https://user-images.githubusercontent.com/24903990/42460365-49ee709a-8363-11e8-9fdd-c917ad90492c.JPG)

Pruebas capturadas----
![imagen](https://user-images.githubusercontent.com/24903990/42460381-544005c2-8363-11e8-87f0-4d68e32307c2.png)

**Comment by jgutierrez01** [comment]
Favor de validarlo nuevamente
