### ISSUE TITLE
Complemento Recepción : Colada

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#3]
Al crear una nueva colada en el modulo de complemento de la recepción, marca el siguiente error: Mensaje de error: An error occurred while updating the entries. See the inner exception for details., no se puso fabricante porque no viene como obligatorio
![colada_erro1](https://user-images.githubusercontent.com/24903990/30924059-435ad730-a373-11e7-8d06-98ffbfde7eb5.jpg)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)
