### ISSUE TITLE
Capturas Pruebas para spool con sistema config spool

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#300]
El spool F456-001 , en la parte de captura pruebas x lotes no despliega los lotes ni las fecha lote, siendo que en avance se crearon los lotes, igualmente en la parte de captura pruebas x spool dice no cuenta con capturas ese spool

--Pruebas x lote--
![imagen](https://user-images.githubusercontent.com/24903990/42462820-fc3c405a-8369-11e8-9b35-2ebd0d5e9d42.png)

--Pruebas x spool..
![imagen](https://user-images.githubusercontent.com/24903990/42462843-0b96809c-836a-11e8-884d-414d8a4b520a.png)

**Comment by jgutierrez01** [comment]
Favor de validarlo nuevamente
