### ISSUE TITLE
Complemento Recepción : Colada y MTR

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#4]
![errormaterial1](https://user-images.githubusercontent.com/24903990/30924099-6a2f0aac-a373-11e7-9f95-2a5800810629.JPG)
![errormaterial1_1](https://user-images.githubusercontent.com/24903990/30924098-6a2eea68-a373-11e7-9959-f372f3d85d48.JPG)

al momento que genero la nueva colada y el mtr, no aparece la informacion de cedula y tipo de acero

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)

**Comment by SAMBugs** [comment]
Realice todo el proceso nuevamente(tambien genere mis item codes de tipo accesorio y de tipo tubo) , genere el mismo escenario, 1 accesorio , 2 tubos adjunto evidencia, en caso de seguir el error favor de indicarmelo.
![image](https://user-images.githubusercontent.com/32207618/31060973-88bd6bbe-a6e1-11e7-8786-a8f265ebd00d.png)
![image](https://user-images.githubusercontent.com/32207618/31060986-b7ba3a96-a6e1-11e7-9caf-3b85ddf4e04a.png)
