### ISSUE TITLE
Carga de carro : Zona y Cuadrante

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#44]
al descargar el carro, debe mandar por default la zona y el cuadrante al que corresponde y  desglose de todas las zonas y cuadrantes

![imagen](https://user-images.githubusercontent.com/24903990/32409801-80d6173c-c178-11e7-83c4-7ef3b32a7e78.png)

**Comment by RojasRuben** [comment]
Es por la incongruencia de Cuadrante entre Sam3 y sam2 y también por que no se relaciono la tabla zona con el patio ya en la próxima publicación debería de corregirse.
