### ISSUE TITLE
Captura PL : MM y dimensión promedio

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#5]
Al momento de agregar mas folio de recepción me percate que los accesorios, en la parte de MM y dimension promedio, aparecen en 0 en lugar N/A
![mm_error1](https://user-images.githubusercontent.com/24903990/30924163-9275023c-a373-11e7-9613-3b8cd8e07878.jpg)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)
