### ISSUE TITLE
Carga Carro :Filtro

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#52]
Al filtrar M2 y Kg y querer filtrar el "es diferente de", no se puede escribir nada

![imagen](https://user-images.githubusercontent.com/24903990/32514024-703c0b70-c3c1-11e7-9c3c-6a70092cbc37.png)

**Comment by RojasRuben** [comment]
Como es de tipo numérico solo puedes ingresar números, si te refieres a otro error podríamos tener una conferencia o indícame por este medio con mas detalle a que error te refieres por favor.
