### ISSUE TITLE
Carga de carro : Filtro

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#53]
al filtrar prioridad no me deja escribir ningun tipo de filto

![imagen](https://user-images.githubusercontent.com/24903990/32514593-27232020-c3c3-11e7-9a89-6a5fe50b2792.png)

**Comment by RojasRuben** [comment]
Como es de tipo numérico solo puedes ingresar números, si te refieres a otro error podríamos tener una conferencia o indícame por este medio con mas detalle a que error te refieres por favor.
