### ISSUE TITLE
Descarga de carro: Zona

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#59]
Al seleccionar el carro y despues la zona
![imagen](https://user-images.githubusercontent.com/24903990/32523392-afaa7458-c3e0-11e7-8099-986cafa28a54.png)

aparecen los spool : ODT30001-001 y ODT30001-002
y al seleccionar otra zona, aparecen los mismo spool

![imagen](https://user-images.githubusercontent.com/24903990/32523430-da906e66-c3e0-11e7-808d-9a14762ced8f.png)

**Comment by RojasRuben** [comment]
Miriam en esta pantalla la zona NO es un filtro para la información que se muestra al usuario, es un  filtro para obtener lo cuadrantes porque si no se hace ese filtro , los cuadrantes son demasiados para mostrarlos al usuario y el control que se usa para mostrar los cuadrantes se vuelve lento

**Comment by MiriamdeLeon-Steelgo** [comment]
OK
