### ISSUE TITLE
Complemento Recepción : colada

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#6]
Al momento de agregar un Mtr a una colada, tarda mas de 5 min en cargar el nombre del item code
![mtr_erro1](https://user-images.githubusercontent.com/24903990/30924193-adb130b6-a373-11e7-82bc-d8e0bda27db1.jpg)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)
