### ISSUE TITLE
Incidencias: Bilingues

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#66]
al entrar desde complemento de la recepcion, para levanta una incidencia por NU,
![imagen](https://user-images.githubusercontent.com/24903990/32557921-2d406796-c469-11e7-9b56-aa06ae35471b.png)

 me manda a la pantalla de incidencia pero sin los botones de traduccion, siendo que ese proyecto es bilingue

![imagen](https://user-images.githubusercontent.com/24903990/32557903-1af243a2-c469-11e7-8bd1-7414b2855d90.png)

pero si entro desde incidencia directo, si me abre con los botones bilingues 

![imagen](https://user-images.githubusercontent.com/24903990/32557945-3cf35946-c469-11e7-8996-ebe25fd331f5.png)

**Comment by emartinezd** [comment]
Nunca se notifico este caso de uso, pero lo reviso
