### ISSUE TITLE
Incidencias: Tipo de Incidencias

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#67]
al desplegar el catalogo de tipo de incidencias y seleccionar NU, tarda alrededor de 9 min en cargar

![imagen](https://user-images.githubusercontent.com/24903990/32566704-5e2a5d84-c47e-11e7-95ab-6664ddad3b5d.png)

**Comment by emartinezd** [comment]
Eso cuando empece el desarrollo, se tardaba demsiado tiempo, por que son muchos numeros unicos ,se tarda pero no mucho, acabo de realizar el proceso 3 veces y no tardo mas de 30 seg

**Comment by MiriamdeLeon-Steelgo** [comment]
me tardo 40 seg 👍
