### ISSUE TITLE
Captura PL : Carga Masiva

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#7]
Al cargar masivamente no aparece la informacion cargada
![error_cargamasiva](https://user-images.githubusercontent.com/24903990/30924228-c4c92d6c-a373-11e7-9395-75f8c904bd80.JPG)
![error_cargamasiva2](https://user-images.githubusercontent.com/24903990/30924227-c4add454-a373-11e7-9be6-998fcf5bd93d.JPG)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)

**Comment by MiriamdeLeon-Steelgo** [comment]
![error_cargamasiva1](https://user-images.githubusercontent.com/24903990/31182582-e1ab51a0-a8e9-11e7-9ccb-e8e5261d2873.jpg)
@RojasRuben  es un nuevo folio intente hacer la carga masiva, y solo cargo esto

**Comment by MiriamdeLeon-Steelgo** [comment]
![diapositiva1](https://user-images.githubusercontent.com/24903990/31282514-6de1dc5e-aa78-11e7-8f93-d8d41be3b5e7.JPG)
![diapositiva2](https://user-images.githubusercontent.com/24903990/31282515-6de47f72-aa78-11e7-834d-ecb49fbc3dcb.JPG)

Te muestro un ejemplo en produccion donde si se carga la cantidad y en QA no

**Comment by MiriamdeLeon-Steelgo** [comment]
![diapositiva1](https://user-images.githubusercontent.com/24903990/31295863-d1d00380-aaa5-11e7-9d7a-4a41c310945b.JPG)
![diapositiva2](https://user-images.githubusercontent.com/24903990/31295862-d1cb6af0-aaa5-11e7-86d4-a0f0d1adde6b.JPG)

@RojasRuben  no se si estoy mal yo o que pero ya hice 2 pruebas, en QA realice la carga masiva y siempre que hago la carga un item (en la columna de item ) me aparece el diametro1 y diametro2, al querer eliminarlo no me permite
