### ISSUE TITLE
Ok PND: Etiqueta

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#70]
al abrir el Menú de Servicios Técnicos . debe decir OK Pnd , en lugar de OK Fabricación
![imagen](https://user-images.githubusercontent.com/24903990/32612808-d11f5636-c52e-11e7-9e22-78b1c2dae22b.png)

**Comment by emartinezd** [comment]
No es bug, es cambio

**Comment by MiriamdeLeon-Steelgo** [comment]
uy perdon jaja me dijeron que lo subiera
