### ISSUE TITLE
Ok Pnd: Proyecto

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#71]
Al seleccionar el proyecto y poner el spoolcontiene = 09
muestra los nombre de spool en lugar del numero de control, y ademas muestra spool que no pertenecen a ese proyecto
![imagen](https://user-images.githubusercontent.com/24903990/32613273-12b8d972-c530-11e7-8be7-40a3dcdbcb55.png)

![imagen](https://user-images.githubusercontent.com/24903990/32613400-6f3babde-c530-11e7-90ca-9bc5229a78e2.png)

**Comment by emartinezd** [comment]
Lo del nombre del spool, es correcto por que asi se pidio, lo del proyecto no
