### ISSUE TITLE
Orden de Almacenaje 

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#8]
Al momento de darle generar orden de almacenaje me marca el error: Mensaje de error: Object reference not set to an instance of an object. Y las cantidas las pone en 0
![ordenalmacenaje_erro1](https://user-images.githubusercontent.com/24903990/30924257-d70e4570-a373-11e7-8d86-78f9b0c2d901.jpg)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)
