### ISSUE TITLE
SHOP: Vista

### ISSUE THREAD

**Issue by Estefania-steelgo** [SAMBugs/Bugs#80]
en donde seleccionas de agregar y editar modificacion para que se vean un poco mas grandes y en donde agregas el numero de control falta la letra del proyecto seleccionado

![image](https://user-images.githubusercontent.com/33491326/32691917-c3ee2d5a-c6d4-11e7-82e0-56f3cd755f38.png)

**Comment by jgutierrez01** [comment]
Favor de validar
