### ISSUE TITLE
SHOP:Agregar cuadrante

### ISSUE THREAD

**Issue by Estefania-steelgo** [SAMBugs/Bugs#81]
En Agregar despues de que no le puse el proyecto me marco error de no haberlo puesto ya se lo pongo para seguir y selecciono cuadrante y quiero agregarlo me arroja error
![image](https://user-images.githubusercontent.com/33491326/32692001-1f2c6c3a-c6d6-11e7-8497-c196cdcb8fdf.png)

![image](https://user-images.githubusercontent.com/33491326/32691996-12453c22-c6d6-11e7-9191-cabd37fd12b1.png)

**Comment by jgutierrez01** [comment]
favor de validar
