### ISSUE TITLE
SHOP:AgregarNumerodeControl

### ISSUE THREAD

**Issue by Estefania-steelgo** [SAMBugs/Bugs#84]
Solo volvi a empezar y me volvio a arrojar el error con agregar un numero de control

![image](https://user-images.githubusercontent.com/33491326/32692180-110481bc-c6d9-11e7-8bb8-192d1d444a01.png)
![image](https://user-images.githubusercontent.com/33491326/32692183-18fda70e-c6d9-11e7-9335-d5d3a83d178b.png)

**Comment by jgutierrez01** [comment]
favor de validar
