### ISSUE TITLE
SHOP:Lentitud

### ISSUE THREAD

**Issue by Estefania-steelgo** [SAMBugs/Bugs#85]
Cuando quiero eliminar un numero de control que ya tiene SQ se tarda en eliminar y yair lo quiere mas rapido

![image](https://user-images.githubusercontent.com/33491326/32692207-63fefdfc-c6d9-11e7-9108-0dd7a1a57ffd.png)

![image](https://user-images.githubusercontent.com/33491326/32692215-86105e2c-c6d9-11e7-8953-f99ffe86d113.png)

**Comment by jgutierrez01** [comment]
Favor de Validar
