### ISSUE TITLE
Inspeccion Dimensional : Lentitud

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#86]
Al momento de guardar la inspección dimensional (solo tiene 3 numero de control)
tarda en guardar alrededor de 30min

![imagen](https://user-images.githubusercontent.com/24903990/32741321-7cceba78-c86b-11e7-9d19-0d3a849f928d.png)

**Comment by emartinezd** [comment]
Acabo de realizar la misma prueba, y no se tardo ni 5 segundos, favor de volver a revisarlo
