### ISSUE TITLE
Captura PL : Busqueda

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#9]
Al buscar un item code en el area de busqueda, no da para realizar la busqueda, se checo en varios folio de recepción y no daba para la busqueda, igualmente para descripción, itc steelgo
![error_busqueda1](https://user-images.githubusercontent.com/24903990/30924290-f009c018-a373-11e7-82e2-162fde53a534.jpg)

**Comment by SAMBugs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spring 1](https://trello.com/c/6CBPDucS/1-spring-1)
