### ISSUE TITLE
Embarque : Preparacion Embarque - Proveedor

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [SAMBugs/Bugs#97]
en la parte de preparacion de embarque al crear un proveedor marca el siguiente error
![imagen](https://user-images.githubusercontent.com/24903990/32850193-15bcad62-c9f7-11e7-81f8-7d78479f1ffa.png)

**Comment by emartinezd** [comment]
Solo es con ese nombre? por que a mi me dejo crear proveedor sin problema

**Comment by MiriamdeLeon-Steelgo** [comment]
ya probe y ya funciono
